/* ==========================================================================
   ISLAND PROTOCOL: PRESIDENTIAL EXTRACTION
   20_render.js - IP.Renderer : WebGL2 / GLSL ES 3.00 deferred-ish forward+
                  renderer with PBR, CSM, SSAO, volumetrics, procedural
                  GPU-synthesised material library, HDR post stack.

   Owner: Agent C. Exposes ONLY IP.Renderer.

   PIPELINE (per frame, in order)
     0. cull + bucket + sort draw lists            (zero heap allocation)
     1. cascaded shadow maps (1/2/3 cascades by quality)
     2. depth prepass into the HDR FBO depth attachment  (quality >= 1)
     3. SSAO (half res) + bilateral blur           (quality >= 1)
     4. opaque forward+ PBR pass (LEQUAL, depth write off if prepass ran)
     5. skybox from the prefiltered procedural environment cubemap
     6. volumetric light shafts (half res, dithered, temporally jittered)
        additively blitted into the HDR target     (quality == 2)
     7. depth blit -> depthCopy (so transparent/sprite passes can sample it)
     8. transparent pass, back-to-front, depth-test / no depth-write
     9. GPU-instanced sprite/particle pass (alpha batch then additive batch)
    10. luminance downsample -> 1x1 -> temporal adaptation (auto exposure)
    11. bright pass -> 3-mip separable gaussian bloom
    12. composite: bloom + ACES + grade + CA + vignette + grain + rain lens
        + hurt / flashbang / lightning -> backbuffer

   HARD RULES OBEYED: no modules, no external assets, no network, single IIFE,
   ASCII only, node --check clean, nothing touched on window.
   ========================================================================== */
var IP = (typeof IP !== 'undefined' && IP) || {};
(function () {
  'use strict';

  var M4 = IP.M4, V3 = IP.V3, Q = IP.Q, Util = IP.Util, Noise = IP.Noise, Rand = IP.Rand;

  /* ======================================================================
     CONSTANTS / TUNING
     ====================================================================== */

  var MAX_LIGHTS = 48;          // hard cap, matches the std140 Lights block
  var MAX_VOL_LIGHTS = 4;       // point lights that contribute to volumetrics
  var MAX_DRAWS = 4096;         // per-frame draw item capacity (opaque+shadow)
  var MAX_TRANSPARENT = 1024;
  var MAX_SPRITES = 8192;       // per blend batch
  var SPRITE_STRIDE = 12;       // floats per sprite instance
  var TEXGEN_SIZE = 512;        // procedural material array resolution
  var TEX_LAYERS = 14;
  var ENV_SIZE = 128;           // environment cubemap face size
  var ENV_MIPS = 6;             // 128,64,32,16,8,4  (last mip ~ irradiance)
  var SSAO_KERNEL = 20;
  var VOL_STEPS_HI = 24;

  /* Material texture id -> array layer. Order is load-bearing: it must match
     the if/else chain inside the texgen fragment shader. */
  var TEX_IDS = ['none', 'concrete', 'metal', 'rust', 'wood', 'dirt', 'rock',
                 'foliage', 'tile', 'flesh', 'fabric', 'glass', 'grate', 'blood'];
  var TEX_INDEX = {};
  (function () { for (var i = 0; i < TEX_IDS.length; i++) { TEX_INDEX[TEX_IDS[i]] = i; } })();

  /* Quality presets. Index == scene.quality. */
  var QUALITY = [
    { /* 0 low / mobile */
      cascades: 1, shadowSize: 512, prepass: false, ssao: false, volumetric: false,
      bloomMips: 1, lights: 8, triplanar: false, pcf: 1, softParticles: false,
      ssaoScale: 0.5, volScale: 0.5, aniso: 2
    },
    { /* 1 medium */
      cascades: 2, shadowSize: 1024, prepass: true, ssao: true, volumetric: false,
      bloomMips: 3, lights: 24, triplanar: true, pcf: 1, softParticles: true,
      ssaoScale: 0.5, volScale: 0.5, aniso: 4
    },
    { /* 2 high */
      cascades: 3, shadowSize: 2048, prepass: true, ssao: true, volumetric: true,
      bloomMips: 3, lights: 48, triplanar: true, pcf: 2, softParticles: true,
      ssaoScale: 0.5, volScale: 0.5, aniso: 16
    }
  ];

  /* Fixed vertex attribute locations, shared by every mesh program. */
  var A_POS = 0, A_NRM = 1, A_UV = 2, A_COL = 3;
  var A_INST_A = 4, A_INST_B = 5, A_INST_C = 6;

  /* Uniform block binding points. */
  var UBO_FRAME = 0, UBO_LIGHTS = 1;

  /* Texture units (kept stable so sampler uniforms are set once at link). */
  var TU_ALBEDO = 0, TU_NORMAL = 1, TU_ORM = 2, TU_SHADOW = 3, TU_ENV = 4,
      TU_AO = 5, TU_DEPTH = 6, TU_NOISE = 7, TU_SRC = 8, TU_BLOOM = 9,
      TU_VOL = 10, TU_LUM = 11;

  /* ======================================================================
     std140 FRAME UNIFORM BLOCK LAYOUT  (736 bytes / 184 floats)
     ----------------------------------------------------------------------
       float idx  name
         0   uView          mat4
        16   uProj          mat4
        32   uViewProj      mat4
        48   uInvView       mat4
        64   uInvProj       mat4
        80   uPrevViewProj  mat4
        96   uCascade0      mat4
       112   uCascade1      mat4
       128   uCascade2      mat4
       144   uCamPos        vec4  (xyz camera world pos, w = scene.time)
       148   uSunDir        vec4  (xyz normalised TO-light dir, w = intensity)
       152   uSunCol        vec4  (rgb sun colour, w = shadow strength 0..1)
       156   uAmbient       vec4  (rgb ambient, w = ssao intensity)
       160   uFogCol        vec4  (rgb fog colour, w = fog density)
       164   uFogParams     vec4  (height, heightFalloff, near, far)
       168   uScreen        vec4  (w, h, 1/w, 1/h)
       172   uMisc          vec4  (quality, activeLightCount, exposure, ssaoOn)
       176   uCascadeSplits vec4  (split0, split1, split2, frameIndex)
       180   uMisc2         vec4  (lightning, normalOffset, depthBias, 1/shadowSize)
     ====================================================================== */
  var FRAME_FLOATS = 184;
  var F_VIEW = 0, F_PROJ = 16, F_VP = 32, F_INVVIEW = 48, F_INVPROJ = 64,
      F_PREVVP = 80, F_CASC0 = 96, F_CASC1 = 112, F_CASC2 = 128,
      F_CAMPOS = 144, F_SUNDIR = 148, F_SUNCOL = 152, F_AMBIENT = 156,
      F_FOGCOL = 160, F_FOGPARAMS = 164, F_SCREEN = 168, F_MISC = 172,
      F_SPLITS = 176, F_MISC2 = 180;

  /* std140 LIGHTS BLOCK: vec4 uLightPos[48] (xyz pos, w range)
                          vec4 uLightCol[48] (rgb colour * intensity, w flags) */
  var LIGHT_FLOATS = MAX_LIGHTS * 4 * 2;

  /* ======================================================================
     SHADER SOURCE
     Every source begins with the literal '#version 300 es\n' as its FIRST
     characters - GLSL ES requires the directive on line 1, column 1.
     ====================================================================== */
  var VER = '#version 300 es\n';

  var CH_PRECISION = [
    'precision highp float;',
    'precision highp int;',
    'precision highp sampler2D;',
    'precision highp sampler2DArray;',
    'precision highp samplerCube;',
    '#define PI 3.14159265359',
    '#define TAU 6.28318530718',
    ''].join('\n');

  var CH_PRECISION_SHADOWSAMP = CH_PRECISION +
    'precision highp sampler2DArrayShadow;\n';

  /* --- the Frame block. Byte-identical text in every consumer. ---------- */
  var CH_FRAME = [
    'layout(std140) uniform Frame {',
    '  mat4 uView;',
    '  mat4 uProj;',
    '  mat4 uViewProj;',
    '  mat4 uInvView;',
    '  mat4 uInvProj;',
    '  mat4 uPrevViewProj;',
    '  mat4 uCascade0;',
    '  mat4 uCascade1;',
    '  mat4 uCascade2;',
    '  vec4 uCamPos;',
    '  vec4 uSunDir;',
    '  vec4 uSunCol;',
    '  vec4 uAmbient;',
    '  vec4 uFogCol;',
    '  vec4 uFogParams;',
    '  vec4 uScreen;',
    '  vec4 uMisc;',
    '  vec4 uCascadeSplits;',
    '  vec4 uMisc2;',
    '};',
    ''].join('\n');

  var CH_LIGHTS = [
    'layout(std140) uniform Lights {',
    '  vec4 uLightPos[48];',
    '  vec4 uLightCol[48];',
    '};',
    ''].join('\n');

  /* --- tileable procedural noise, used by texgen + sky + lens fx -------- */
  var CH_NOISE = [
    'float hash11(float p){ p = fract(p * 0.1031); p *= p + 33.33; p *= p + p; return fract(p); }',
    'float hash12(vec2 p){',
    '  vec3 p3 = fract(vec3(p.xyx) * 0.1031);',
    '  p3 += dot(p3, p3.yzx + 33.33);',
    '  return fract((p3.x + p3.y) * p3.z);',
    '}',
    'vec2 hash22(vec2 p){',
    '  vec3 p3 = fract(vec3(p.xyx) * vec3(0.1031, 0.1030, 0.0973));',
    '  p3 += dot(p3, p3.yzx + 33.33);',
    '  return fract((p3.xx + p3.yz) * p3.zy);',
    '}',
    'float hash13(vec3 p3){',
    '  p3 = fract(p3 * 0.1031);',
    '  p3 += dot(p3, p3.zyx + 31.32);',
    '  return fract((p3.x + p3.y) * p3.z);',
    '}',
    /* tileable value noise: lattice coords wrapped by "per" */
    'float vnoiseT(vec2 p, float per){',
    '  vec2 i = floor(p), f = fract(p);',
    '  f = f * f * (3.0 - 2.0 * f);',
    '  float a = hash12(mod(i, per));',
    '  float b = hash12(mod(i + vec2(1.0, 0.0), per));',
    '  float c = hash12(mod(i + vec2(0.0, 1.0), per));',
    '  float d = hash12(mod(i + vec2(1.0, 1.0), per));',
    '  return mix(mix(a, b, f.x), mix(c, d, f.x), f.y);',
    '}',
    'float fbmT(vec2 p, float per, int oct){',
    '  float a = 0.5, s = 0.0, n = 0.0;',
    '  for (int k = 0; k < 8; k++){',
    '    if (k >= oct) break;',
    '    s += a * vnoiseT(p, per); n += a;',
    '    a *= 0.5; p *= 2.0; per *= 2.0;',
    '  }',
    '  return s / max(n, 1e-4);',
    '}',
    /* ridged fbm: veins, cracks, rock fractures */
    'float ridgeT(vec2 p, float per, int oct){',
    '  float a = 0.5, s = 0.0, n = 0.0;',
    '  for (int k = 0; k < 8; k++){',
    '    if (k >= oct) break;',
    '    float v = 1.0 - abs(vnoiseT(p, per) * 2.0 - 1.0);',
    '    s += a * v * v; n += a;',
    '    a *= 0.5; p *= 2.0; per *= 2.0;',
    '  }',
    '  return s / max(n, 1e-4);',
    '}',
    /* tileable worley: returns .x = F1, .y = F2 - F1 (cell edge distance) */
    'vec2 worleyT(vec2 p, float per){',
    '  vec2 i = floor(p), f = fract(p);',
    '  float f1 = 8.0, f2 = 8.0;',
    '  for (int y = -1; y <= 1; y++){',
    '    for (int x = -1; x <= 1; x++){',
    '      vec2 o = vec2(float(x), float(y));',
    '      vec2 h = hash22(mod(i + o, per));',
    '      vec2 d = o + h - f;',
    '      float dd = dot(d, d);',
    '      if (dd < f1) { f2 = f1; f1 = dd; } else if (dd < f2) { f2 = dd; }',
    '    }',
    '  }',
    '  f1 = sqrt(f1); f2 = sqrt(f2);',
    '  return vec2(f1, f2 - f1);',
    '}',
    /* cell id, for per-cell colour jitter (leaves, rock, tiles) */
    'vec3 worleyCell(vec2 p, float per){',
    '  vec2 i = floor(p), f = fract(p);',
    '  float f1 = 8.0; vec2 best = vec2(0.0);',
    '  for (int y = -1; y <= 1; y++){',
    '    for (int x = -1; x <= 1; x++){',
    '      vec2 o = vec2(float(x), float(y));',
    '      vec2 c = mod(i + o, per);',
    '      vec2 h = hash22(c);',
    '      vec2 d = o + h - f;',
    '      float dd = dot(d, d);',
    '      if (dd < f1) { f1 = dd; best = c; }',
    '    }',
    '  }',
    '  return vec3(sqrt(f1), best);',
    '}',
    ''].join('\n');

  /* --- height-fog + tonemap helpers shared by lit passes ---------------- */
  var CH_FOG = [
    /* Analytic exponential height fog. Integrates exp(-b*(y-h0)) along the',
       view ray so vertical motion through the fog slab is continuous. */
    'float heightFog(vec3 camP, vec3 wp){',
    '  vec3 d = wp - camP;',
    '  float dist = length(d);',
    '  if (dist < 1e-4) return 0.0;',
    '  float b = max(uFogParams.y, 1e-4);',
    '  float h0 = uFogParams.x;',
    '  float dens = uFogCol.w;',
    '  float fy = exp(-b * (camP.y - h0));',
    '  float dy = d.y;',
    '  float t = (abs(dy) > 1e-4) ? (1.0 - exp(-b * dy)) / (b * dy) : 1.0;',
    '  float amount = dens * dist * fy * t;',
    '  return 1.0 - exp(-max(amount, 0.0));',
    '}',
    ''].join('\n');

  var CH_PBR = [
    /* Cook-Torrance: GGX NDF + Smith height-correlated visibility + Schlick */
    'float D_GGX(float NoH, float a){',
    '  float a2 = a * a;',
    '  float d = (NoH * a2 - NoH) * NoH + 1.0;',
    '  return a2 / max(PI * d * d, 1e-7);',
    '}',
    'float V_SmithGGX(float NoV, float NoL, float a){',
    '  float a2 = a * a;',
    '  float gv = NoL * sqrt(NoV * NoV * (1.0 - a2) + a2);',
    '  float gl = NoV * sqrt(NoL * NoL * (1.0 - a2) + a2);',
    '  return 0.5 / max(gv + gl, 1e-6);',
    '}',
    'vec3 F_Schlick(vec3 f0, float u){',
    '  float f = pow(1.0 - u, 5.0);',
    '  return f0 + (vec3(1.0) - f0) * f;',
    '}',
    /* Karis analytic split-sum environment BRDF approximation */
    'vec2 envBRDF(float NoV, float rough){',
    '  vec4 c0 = vec4(-1.0, -0.0275, -0.572, 0.022);',
    '  vec4 c1 = vec4(1.0, 0.0425, 1.04, -0.04);',
    '  vec4 r = rough * c0 + c1;',
    '  float a004 = min(r.x * r.x, exp2(-9.28 * NoV)) * r.x + r.y;',
    '  return vec2(-1.04, 1.04) * a004 + r.zw;',
    '}',
    /* smooth range window on top of physical inverse-square falloff */
    'float lightAtten(float dist, float range){',
    '  float f = dist / max(range, 1e-3);',
    '  float w = clamp(1.0 - f * f * f * f, 0.0, 1.0);',
    '  w *= w;',
    '  return w / (dist * dist + 0.02);',
    '}',
    ''].join('\n');

  /* ------------------------------------------------------------------ */
  /* Fullscreen triangle vertex shader (no attributes, gl_VertexID based) */
  var VS_FULLSCREEN = VER + [
    'out vec2 vUV;',
    'void main(){',
    '  vec2 p = vec2(float((gl_VertexID << 1) & 2), float(gl_VertexID & 2));',
    '  vUV = p;',
    '  gl_Position = vec4(p * 2.0 - 1.0, 0.0, 1.0);',
    '}',
    ''].join('\n');

  /* ==================== PROCEDURAL MATERIAL TEXTURE GEN ================= */
  /* One MRT draw per layer writes albedo(sqrt-encoded) / normal+height / ORM.
     Everything is authored tileable so triplanar world-space repeats do not
     seam. Height is evaluated 4 extra times per pixel for the sobel normal. */
  var FS_TEXGEN = VER + CH_PRECISION + CH_NOISE + [
    'in vec2 vUV;',
    'layout(location = 0) out vec4 oAlbedo;',
    'layout(location = 1) out vec4 oNormal;',
    'layout(location = 2) out vec4 oORM;',
    'uniform int uLayer;',
    'uniform sampler2D uNoiseTex;   // CPU-side IP.Noise atlas: r=fbm g=worley b=perlin a=white',
    '',
    '// ---- height field per material (drives the sobel normal map) ------',
    'float heightAt(int L, vec2 p){',
    '  if (L == 1){ // CONCRETE ------------------------------------------',
    '    float h = fbmT(p * 6.0, 6.0, 5) * 0.65 + fbmT(p * 34.0, 34.0, 3) * 0.18;',
    '    vec2 w = worleyT(p * 9.0, 9.0);',
    '    h -= smoothstep(0.45, 0.05, w.x) * 0.30;            // blown-out pits',
    '    float crack = ridgeT(p * 3.0 + 11.0, 3.0, 4);',
    '    h -= smoothstep(0.72, 0.97, crack) * 0.45;          // hairline cracks',
    '    return h;',
    '  } else if (L == 2){ // METAL PLATE ---------------------------------',
    '    vec2 g = fract(p * 3.0);',
    '    float seam = min(min(g.x, 1.0 - g.x), min(g.y, 1.0 - g.y));',
    '    float h = 0.55 + fbmT(vec2(p.x * 90.0, p.y * 6.0), 90.0, 3) * 0.06;',
    '    h -= (1.0 - smoothstep(0.0, 0.035, seam)) * 0.5;    // plate seams',
    '    vec2 rp = fract(p * 3.0) - 0.5;',
    '    vec2 rq = abs(rp) - 0.40;',
    '    float riv = length(max(rq, 0.0));',
    '    h += (1.0 - smoothstep(0.0, 0.035, riv)) * 0.35;    // corner rivets',
    '    return h;',
    '  } else if (L == 3){ // RUST ----------------------------------------',
    '    float base = 0.5 + fbmT(p * 8.0, 8.0, 5) * 0.25;',
    '    vec2 w = worleyT(p * 6.0, 6.0);',
    '    float scab = smoothstep(0.55, 0.1, w.x);',
    '    base -= scab * 0.35 * (0.5 + 0.5 * fbmT(p * 40.0, 40.0, 3));',
    '    return base;',
    '  } else if (L == 4){ // WOOD ----------------------------------------',
    '    float plank = floor(p.y * 4.0);',
    '    vec2 q = vec2(p.x + hash11(plank) * 0.37, p.y);',
    '    float grain = fbmT(vec2(q.x * 3.0, q.y * 48.0), 48.0, 4);',
    '    float rings = fract(q.x * 7.0 + grain * 2.4);',
    '    float h = 0.55 + (rings * rings) * 0.22 + grain * 0.1;',
    '    float gap = abs(fract(p.y * 4.0) - 0.5);',
    '    h -= smoothstep(0.47, 0.5, gap) * 0.35;             // plank gaps',
    '    vec2 kn = worleyT(p * 3.0 + 5.0, 3.0);',
    '    h -= smoothstep(0.25, 0.0, kn.x) * 0.25;            // knots',
    '    return h;',
    '  } else if (L == 5){ // DIRT ----------------------------------------',
    '    float h = fbmT(p * 5.0, 5.0, 6) * 0.7 + fbmT(p * 25.0, 25.0, 3) * 0.25;',
    '    vec2 w = worleyT(p * 22.0, 22.0);',
    '    h += smoothstep(0.4, 0.0, w.x) * 0.22;              // pebbles',
    '    return h;',
    '  } else if (L == 6){ // ROCK ----------------------------------------',
    '    vec2 w = worleyT(p * 4.0, 4.0);',
    '    float h = w.x * 0.55 + fbmT(p * 9.0, 9.0, 5) * 0.35;',
    '    h -= smoothstep(0.12, 0.0, w.y) * 0.4;              // fracture seams',
    '    h += fbmT(p * 40.0, 40.0, 3) * 0.08;',
    '    return h;',
    '  } else if (L == 7){ // FOLIAGE -------------------------------------',
    '    vec3 c = worleyCell(p * 4.0, 4.0);',
    '    float h = 0.6 - c.x * 0.4;',
    '    float vein = ridgeT((p + hash22(c.yz)) * 26.0, 26.0, 3);',
    '    h += vein * 0.14;',
    '    return h;',
    '  } else if (L == 8){ // TILE ----------------------------------------',
    '    vec2 g = fract(p * 6.0);',
    '    float e = min(min(g.x, 1.0 - g.x), min(g.y, 1.0 - g.y));',
    '    float h = smoothstep(0.0, 0.055, e) * 0.55 + 0.2;   // grout recess',
    '    h += fbmT(p * 60.0, 60.0, 2) * 0.03;',
    '    vec2 ch = worleyT(p * 14.0 + 3.0, 14.0);',
    '    h -= smoothstep(0.16, 0.0, ch.x) * 0.35;            // chipped corners',
    '    return h;',
    '  } else if (L == 9){ // FLESH ---------------------------------------',
    '    float h = 0.55 + fbmT(p * 7.0, 7.0, 4) * 0.2;',
    '    float vein = ridgeT(p * 5.0 + 2.0, 5.0, 5);',
    '    h += smoothstep(0.62, 0.95, vein) * 0.28;           // raised veins',
    '    vec2 w = worleyT(p * 13.0, 13.0);',
    '    h += smoothstep(0.3, 0.0, w.x) * 0.30;              // pustules',
    '    return h;',
    '  } else if (L == 10){ // FABRIC -------------------------------------',
    '    float u = fract(p.x * 60.0), v = fract(p.y * 60.0);',
    '    float weave = (sin(u * TAU) * 0.5 + 0.5) * step(fract(p.y * 30.0), 0.5)',
    '                + (sin(v * TAU) * 0.5 + 0.5) * step(0.5, fract(p.y * 30.0));',
    '    return 0.45 + weave * 0.25 + fbmT(p * 70.0, 70.0, 3) * 0.12;',
    '  } else if (L == 11){ // GLASS --------------------------------------',
    '    float h = 0.5 + fbmT(p * 3.0, 3.0, 3) * 0.02;',
    '    float smudge = smoothstep(0.35, 0.9, fbmT(p * 6.0 + 7.0, 6.0, 4));',
    '    h += smudge * 0.02;',
    '    return h;',
    '  } else if (L == 12){ // GRATE --------------------------------------',
    '    vec2 q = p * 8.0;',
    '    q.x += step(1.0, mod(floor(q.y), 2.0)) * 0.5;       // hex-ish offset',
    '    vec2 f = fract(q) - 0.5;',
    '    float d = length(f);',
    '    return smoothstep(0.30, 0.36, d) * 0.7 + 0.15;',
    '  } else if (L == 13){ // BLOOD --------------------------------------',
    '    float pool = fbmT(p * 4.0, 4.0, 5);',
    '    float h = 0.5 + smoothstep(0.42, 0.62, pool) * 0.12;',
    '    h += fbmT(p * 30.0, 30.0, 3) * 0.03;',
    '    return h;',
    '  }',
    '  return 0.5; // NONE',
    '}',
    '',
    '// ---- albedo / ao / roughness / metal / alpha ----------------------',
    'void matSample(int L, vec2 p, out vec3 alb, out float ao, out float rough,',
    '               out float metal, out float alpha){',
    '  alpha = 1.0; metal = 0.0; ao = 1.0; rough = 0.85; alb = vec3(0.6);',
    '  vec4 nz = texture(uNoiseTex, p);   // CPU IP.Noise atlas, adds character',
    '  if (L == 1){ // CONCRETE',
    '    float g = 0.34 + fbmT(p * 6.0, 6.0, 5) * 0.20 + nz.r * 0.06;',
    '    float speck = step(0.86, fbmT(p * 90.0, 90.0, 2));',
    '    g += speck * 0.10;',
    '    vec2 w = worleyT(p * 9.0, 9.0);',
    '    float pit = smoothstep(0.45, 0.05, w.x);',
    '    g -= pit * 0.16;',
    '    float crack = smoothstep(0.72, 0.97, ridgeT(p * 3.0 + 11.0, 3.0, 4));',
    '    g -= crack * 0.22;',
    '    float stain = smoothstep(0.5, 0.85, fbmT(p * 2.5 + 21.0, 2.5, 4));',
    '    alb = mix(vec3(g, g * 0.99, g * 0.95), vec3(0.16, 0.15, 0.13), stain * 0.55);',
    '    rough = 0.88 - speck * 0.08 + crack * 0.06;',
    '    ao = 1.0 - pit * 0.5 - crack * 0.45;',
    '  } else if (L == 2){ // METAL PLATE',
    '    float brush = fbmT(vec2(p.x * 90.0, p.y * 6.0), 90.0, 3);',
    '    float g = 0.42 + brush * 0.14;',
    '    vec2 gr = fract(p * 3.0);',
    '    float seam = 1.0 - smoothstep(0.0, 0.035, min(min(gr.x, 1.0 - gr.x), min(gr.y, 1.0 - gr.y)));',
    '    float grime = smoothstep(0.45, 0.85, fbmT(p * 4.0 + 3.0, 4.0, 4));',
    '    alb = mix(vec3(g * 0.86, g * 0.90, g), vec3(0.09, 0.09, 0.10), seam * 0.7);',
    '    alb = mix(alb, vec3(0.13, 0.12, 0.10), grime * 0.45);',
    '    metal = 1.0 - seam * 0.4 - grime * 0.35;',
    '    rough = 0.30 + brush * 0.18 + grime * 0.35 + seam * 0.25;',
    '    ao = 1.0 - seam * 0.55;',
    '  } else if (L == 3){ // RUST',
    '    vec2 w = worleyT(p * 6.0, 6.0);',
    '    float scab = smoothstep(0.55, 0.1, w.x);',
    '    float fine = fbmT(p * 30.0, 30.0, 4);',
    '    vec3 rustA = vec3(0.30, 0.11, 0.045);',
    '    vec3 rustB = vec3(0.46, 0.22, 0.08);',
    '    vec3 steel = vec3(0.30, 0.31, 0.33);',
    '    alb = mix(steel, mix(rustA, rustB, fine), clamp(scab + fine * 0.45, 0.0, 1.0));',
    '    alb *= 0.75 + nz.g * 0.4;',
    '    metal = (1.0 - scab) * 0.85;',
    '    rough = mix(0.42, 0.95, clamp(scab + fine * 0.3, 0.0, 1.0));',
    '    ao = 1.0 - scab * 0.35;',
    '  } else if (L == 4){ // WOOD',
    '    float plank = floor(p.y * 4.0);',
    '    vec2 q = vec2(p.x + hash11(plank) * 0.37, p.y);',
    '    float grain = fbmT(vec2(q.x * 3.0, q.y * 48.0), 48.0, 4);',
    '    float rings = fract(q.x * 7.0 + grain * 2.4);',
    '    float tone = 0.30 + rings * 0.28 + hash11(plank + 4.0) * 0.12;',
    '    alb = vec3(tone, tone * 0.62, tone * 0.36);',
    '    float rot = smoothstep(0.55, 0.9, fbmT(p * 3.0 + 9.0, 3.0, 4));',
    '    alb = mix(alb, vec3(0.10, 0.10, 0.08), rot * 0.7);',
    '    float gap = smoothstep(0.47, 0.5, abs(fract(p.y * 4.0) - 0.5));',
    '    alb *= 1.0 - gap * 0.85;',
    '    rough = 0.68 + grain * 0.2 + rot * 0.15;',
    '    ao = 1.0 - gap * 0.7 - rot * 0.2;',
    '  } else if (L == 5){ // DIRT',
    '    float c = fbmT(p * 5.0, 5.0, 6);',
    '    vec3 wet = vec3(0.075, 0.062, 0.048);',
    '    vec3 dry = vec3(0.19, 0.155, 0.115);',
    '    alb = mix(wet, dry, smoothstep(0.3, 0.75, c));',
    '    vec2 w = worleyT(p * 22.0, 22.0);',
    '    float peb = smoothstep(0.35, 0.0, w.x);',
    '    alb = mix(alb, vec3(0.24, 0.23, 0.21), peb * 0.7);',
    '    rough = 0.94 - peb * 0.2;',
    '    ao = 1.0 - (1.0 - c) * 0.35;',
    '  } else if (L == 6){ // ROCK',
    '    vec2 w = worleyT(p * 4.0, 4.0);',
    '    float g = 0.20 + w.x * 0.22 + fbmT(p * 9.0, 9.0, 5) * 0.14;',
    '    alb = vec3(g * 1.0, g * 0.99, g * 0.96);',
    '    float moss = smoothstep(0.55, 0.9, fbmT(p * 3.5 + 17.0, 3.5, 4));',
    '    alb = mix(alb, vec3(0.075, 0.115, 0.055), moss * 0.65);',
    '    float seam = smoothstep(0.12, 0.0, w.y);',
    '    alb *= 1.0 - seam * 0.6;',
    '    rough = 0.88 + moss * 0.08;',
    '    ao = 1.0 - seam * 0.6;',
    '  } else if (L == 7){ // FOLIAGE (alpha cut)',
    '    vec3 c = worleyCell(p * 4.0, 4.0);',
    '    float leaf = 1.0 - smoothstep(0.30, 0.42, c.x);',
    '    alpha = leaf;',
    '    float tint = hash12(c.yz);',
    '    vec3 g1 = vec3(0.045, 0.115, 0.038);',
    '    vec3 g2 = vec3(0.10, 0.16, 0.05);',
    '    alb = mix(g1, g2, tint);',
    '    float vein = ridgeT((p + hash22(c.yz)) * 26.0, 26.0, 3);',
    '    alb *= 0.8 + vein * 0.5;',
    '    float dead = smoothstep(0.6, 0.95, fbmT(p * 2.0 + 31.0, 2.0, 3));',
    '    alb = mix(alb, vec3(0.16, 0.11, 0.045), dead);',
    '    rough = 0.72;',
    '    ao = 0.75 + c.x * 0.25;',
    '  } else if (L == 8){ // TILE',
    '    vec2 g = fract(p * 6.0);',
    '    vec2 id = floor(p * 6.0);',
    '    float e = min(min(g.x, 1.0 - g.x), min(g.y, 1.0 - g.y));',
    '    float grout = 1.0 - smoothstep(0.0, 0.055, e);',
    '    float v = hash12(id);',
    '    vec3 tile = mix(vec3(0.30, 0.31, 0.30), vec3(0.44, 0.45, 0.42), v);',
    '    float stain = smoothstep(0.5, 0.9, fbmT(p * 2.0 + 5.0, 2.0, 4));',
    '    tile = mix(tile, vec3(0.10, 0.115, 0.075), stain * 0.6);',
    '    alb = mix(tile, vec3(0.11, 0.105, 0.095), grout);',
    '    vec2 ch = worleyT(p * 14.0 + 3.0, 14.0);',
    '    float chip = smoothstep(0.16, 0.0, ch.x);',
    '    alb = mix(alb, vec3(0.20, 0.19, 0.18), chip);',
    '    rough = mix(0.28 + v * 0.12 + stain * 0.4, 0.92, max(grout, chip));',
    '    ao = 1.0 - grout * 0.55 - chip * 0.3;',
    '  } else if (L == 9){ // FLESH',
    '    float base = fbmT(p * 7.0, 7.0, 4);',
    '    alb = mix(vec3(0.32, 0.10, 0.10), vec3(0.50, 0.22, 0.19), base);',
    '    float vein = smoothstep(0.6, 0.95, ridgeT(p * 5.0 + 2.0, 5.0, 5));',
    '    alb = mix(alb, vec3(0.20, 0.045, 0.06), vein * 0.8);',
    '    vec2 w = worleyT(p * 13.0, 13.0);',
    '    float pus = smoothstep(0.3, 0.0, w.x);',
    '    alb = mix(alb, vec3(0.55, 0.50, 0.22), pus * 0.6);',
    '    rough = 0.34 + base * 0.2 - pus * 0.14;',
    '    ao = 1.0 - vein * 0.25;',
    '  } else if (L == 10){ // FABRIC',
    '    float u = fract(p.x * 60.0), v = fract(p.y * 60.0);',
    '    float weave = (sin(u * TAU) * 0.5 + 0.5) * step(fract(p.y * 30.0), 0.5)',
    '                + (sin(v * TAU) * 0.5 + 0.5) * step(0.5, fract(p.y * 30.0));',
    '    float dye = fbmT(p * 3.0, 3.0, 4);',
    '    alb = mix(vec3(0.085, 0.095, 0.105), vec3(0.16, 0.15, 0.14), dye);',
    '    alb *= 0.7 + weave * 0.45;',
    '    float wear = smoothstep(0.6, 0.95, fbmT(p * 5.0 + 13.0, 5.0, 4));',
    '    alb = mix(alb, vec3(0.055, 0.05, 0.045), wear * 0.6);',
    '    rough = 0.93;',
    '    ao = 0.8 + weave * 0.2;',
    '  } else if (L == 11){ // GLASS',
    '    float smudge = smoothstep(0.35, 0.9, fbmT(p * 6.0 + 7.0, 6.0, 4));',
    '    float dust = fbmT(p * 40.0, 40.0, 3);',
    '    alb = mix(vec3(0.045, 0.055, 0.06), vec3(0.20, 0.21, 0.20), smudge * 0.5 + dust * 0.15);',
    '    rough = 0.045 + smudge * 0.30 + dust * 0.08;',
    '    metal = 0.0;',
    '    ao = 1.0;',
    '  } else if (L == 12){ // GRATE (holes punched with alpha)',
    '    vec2 q = p * 8.0;',
    '    q.x += step(1.0, mod(floor(q.y), 2.0)) * 0.5;',
    '    vec2 f = fract(q) - 0.5;',
    '    float d = length(f);',
    '    alpha = smoothstep(0.30, 0.34, d);',
    '    float edge = 1.0 - smoothstep(0.33, 0.46, d);',
    '    float grime = fbmT(p * 12.0, 12.0, 4);',
    '    alb = mix(vec3(0.20, 0.205, 0.215), vec3(0.11, 0.085, 0.06), grime * 0.7);',
    '    alb *= 1.0 - edge * 0.45;',
    '    metal = 0.9 - grime * 0.4;',
    '    rough = 0.42 + grime * 0.35;',
    '    ao = 1.0 - edge * 0.6;',
    '  } else if (L == 13){ // BLOOD',
    '    float pool = fbmT(p * 4.0, 4.0, 5);',
    '    float wetMask = smoothstep(0.44, 0.62, pool);',
    '    vec3 fresh = vec3(0.26, 0.012, 0.012);',
    '    vec3 dried = vec3(0.085, 0.020, 0.016);',
    '    alb = mix(dried, fresh, wetMask);',
    '    float spat = smoothstep(0.72, 0.95, fbmT(p * 16.0 + 4.0, 16.0, 3));',
    '    alb = mix(alb, fresh * 1.2, spat * 0.6);',
    '    alpha = clamp(smoothstep(0.30, 0.48, pool) + spat, 0.0, 1.0);',
    '    rough = mix(0.80, 0.13, wetMask);',
    '    ao = 1.0 - (1.0 - wetMask) * 0.2;',
    '  } else { // NONE - neutral, lets material albedo speak',
    '    alb = vec3(0.5); rough = 0.8; metal = 0.0; ao = 1.0;',
    '  }',
    '  alb = clamp(alb, vec3(0.0), vec3(1.0));',
    '  rough = clamp(rough, 0.035, 1.0);',
    '  metal = clamp(metal, 0.0, 1.0);',
    '  ao = clamp(ao, 0.0, 1.0);',
    '}',
    '',
    'void main(){',
    '  vec2 p = vUV;',
    '  vec3 alb; float ao, rough, metal, alpha;',
    '  matSample(uLayer, p, alb, ao, rough, metal, alpha);',
    '  float e = 1.0 / float(' + TEXGEN_SIZE + ');',
    '  float hL = heightAt(uLayer, p - vec2(e, 0.0));',
    '  float hR = heightAt(uLayer, p + vec2(e, 0.0));',
    '  float hD = heightAt(uLayer, p - vec2(0.0, e));',
    '  float hU = heightAt(uLayer, p + vec2(0.0, e));',
    '  float hC = heightAt(uLayer, p);',
    '  float strength = (uLayer == 11) ? 0.35 : 3.0;',
    '  vec3 n = normalize(vec3((hL - hR) * strength, (hD - hU) * strength, 2.0 * e * 40.0));',
    '  // sqrt-encode albedo: RGBA8 storage with usable precision in the darks',
    '  oAlbedo = vec4(sqrt(alb), alpha);',
    '  oNormal = vec4(n * 0.5 + 0.5, clamp(hC, 0.0, 1.0));',
    '  oORM = vec4(ao, rough, metal, 1.0);',
    '}',
    ''].join('\n');

  /* ===================== PROCEDURAL SKY / ENVIRONMENT =================== */
  /* Storm-at-night analytic sky. Rendered once into a cubemap; higher mips
     are cone-integrated so they double as roughness-prefiltered radiance and
     (last mip) as a crude irradiance probe. */
  var FS_ENV = VER + CH_PRECISION + CH_NOISE + [
    'in vec2 vUV;',
    'out vec4 oCol;',
    'uniform int uFace;',
    'uniform float uRough;',
    'uniform vec3 uSun;        // direction TO the sun/moon',
    'uniform vec3 uSunColor;',
    'uniform float uTime;',
    'uniform float uLightning;',
    'uniform sampler2D uNoiseTex;',
    '',
    'vec3 faceDir(int f, vec2 uv){',
    '  vec2 c = uv * 2.0 - 1.0;',
    '  if (f == 0) return normalize(vec3( 1.0, -c.y, -c.x));',
    '  if (f == 1) return normalize(vec3(-1.0, -c.y,  c.x));',
    '  if (f == 2) return normalize(vec3( c.x,  1.0,  c.y));',
    '  if (f == 3) return normalize(vec3( c.x, -1.0, -c.y));',
    '  if (f == 4) return normalize(vec3( c.x, -c.y,  1.0));',
    '  return normalize(vec3(-c.x, -c.y, -1.0));',
    '}',
    '',
    '// Overcast storm: near-black blue zenith, slightly warmer sodium haze at',
    '// the horizon, heavy fbm cloud deck, dim moon disc bleeding through.',
    'vec3 skyColor(vec3 d){',
    '  float up = clamp(d.y, -1.0, 1.0);',
    '  vec3 zenith  = vec3(0.006, 0.011, 0.024);',
    '  vec3 horizon = vec3(0.030, 0.040, 0.062);',
    '  vec3 ground  = vec3(0.008, 0.008, 0.009);',
    '  vec3 col = mix(horizon, zenith, pow(clamp(up, 0.0, 1.0), 0.55));',
    '  col = mix(ground, col, smoothstep(-0.12, 0.06, up));',
    '  // sodium-vapour glow bleeding up from the facility, hugging the horizon',
    '  float hz = pow(1.0 - clamp(abs(up), 0.0, 1.0), 7.0);',
    '  col += vec3(0.055, 0.036, 0.016) * hz;',
    '  // two scrolling cloud decks projected on the sky dome',
    '  if (up > -0.05) {',
    '    vec2 cp = d.xz / max(abs(d.y) + 0.16, 0.16);',
    '    float c1 = fbmT(cp * 0.9 + vec2(uTime * 0.006, uTime * 0.0025), 512.0, 6);',
    '    float c2 = fbmT(cp * 2.3 - vec2(uTime * 0.011, 0.0), 512.0, 5);',
    '    float deck = clamp(c1 * 0.75 + c2 * 0.35, 0.0, 1.0);',
    '    float mask = smoothstep(-0.05, 0.30, up);',
    '    float thick = smoothstep(0.35, 0.85, deck) * mask;',
    '    vec3 cloudLit = vec3(0.055, 0.062, 0.080);',
    '    vec3 cloudDark = vec3(0.010, 0.013, 0.020);',
    '    col = mix(col, mix(cloudDark, cloudLit, deck), thick * 0.85);',
    '    // lightning lights the deck from inside',
    '    col += vec3(0.55, 0.62, 0.85) * uLightning * thick * (0.35 + deck * 0.9);',
    '  }',
    '  // moon / dim sun disc + broad glow, heavily attenuated by the deck',
    '  float sd = max(dot(d, uSun), 0.0);',
    '  col += uSunColor * pow(sd, 900.0) * 6.0;',
    '  col += uSunColor * pow(sd, 8.0) * 0.14;',
    '  col += uSunColor * pow(sd, 2.0) * 0.03;',
    '  col += vec3(0.30, 0.36, 0.55) * uLightning * 0.25;',
    '  return max(col, vec3(0.0));',
    '}',
    '',
    'void main(){',
    '  vec3 N = faceDir(uFace, vUV);',
    '  if (uRough < 0.01){',
    '    oCol = vec4(skyColor(N), 1.0);',
    '    return;',
    '  }',
    '  // cone-integrate the analytic sky: cheap, exact-enough prefilter',
    '  vec3 up = abs(N.y) < 0.95 ? vec3(0.0, 1.0, 0.0) : vec3(1.0, 0.0, 0.0);',
    '  vec3 T = normalize(cross(up, N));',
    '  vec3 B = cross(N, T);',
    '  float a = uRough * uRough;',
    '  vec3 sum = vec3(0.0);',
    '  float wsum = 0.0;',
    '  const int NS = 24;',
    '  for (int i = 0; i < NS; i++){',
    '    float fi = float(i);',
    '    float u1 = fract(fi * 0.618033988 + 0.5);',
    '    float u2 = (fi + 0.5) / float(NS);',
    '    float phi = u1 * TAU;',
    '    float ct = sqrt((1.0 - u2) / (1.0 + (a * a - 1.0) * u2));',
    '    float st = sqrt(max(1.0 - ct * ct, 0.0));',
    '    vec3 H = normalize(T * (st * cos(phi)) + B * (st * sin(phi)) + N * ct);',
    '    vec3 L = normalize(2.0 * dot(N, H) * H - N);',
    '    float nl = max(dot(N, L), 0.0);',
    '    if (nl > 0.0){ sum += skyColor(L) * nl; wsum += nl; }',
    '  }',
    '  oCol = vec4(sum / max(wsum, 1e-4), 1.0);',
    '}',
    ''].join('\n');

  /* skybox draw: samples the finished cubemap so the sky and the IBL agree */
  var VS_SKY = VER + CH_FRAME + [
    'out vec3 vDir;',
    'void main(){',
    '  vec2 p = vec2(float((gl_VertexID << 1) & 2), float(gl_VertexID & 2));',
    '  vec2 ndc = p * 2.0 - 1.0;',
    '  vec4 v = uInvProj * vec4(ndc, 1.0, 1.0);',
    '  vDir = mat3(uInvView) * (v.xyz / v.w);',
    '  gl_Position = vec4(ndc, 1.0, 1.0);',
    '}',
    ''].join('\n');

  var FS_SKY = VER + CH_PRECISION + CH_FRAME + [
    'in vec3 vDir;',
    'out vec4 oCol;',
    'uniform samplerCube uEnv;',
    'void main(){',
    '  vec3 d = normalize(vDir);',
    '  vec3 c = textureLod(uEnv, d, 0.0).rgb;',
    '  // fade the low sky into the fog colour so the horizon line dissolves',
    '  float h = smoothstep(0.14, -0.03, d.y);',
    '  c = mix(c, uFogCol.rgb, h * 0.92);',
    '  c += uFogCol.rgb * uMisc2.x * 1.4;',
    '  oCol = vec4(c, 1.0);',
    '}',
    ''].join('\n');

  /* =========================== SHADOW / DEPTH ========================== */
  var VS_DEPTH = VER + CH_FRAME + [
    'layout(location = 0) in vec3 aPos;',
    'uniform mat4 uModel;',
    'uniform mat4 uLightVP;   // identity-ish for the camera prepass',
    'uniform float uUseLightVP;',
    'void main(){',
    '  vec4 wp = uModel * vec4(aPos, 1.0);',
    '  mat4 vp = (uUseLightVP > 0.5) ? uLightVP : uViewProj;',
    '  gl_Position = vp * wp;',
    '}',
    ''].join('\n');

  var FS_DEPTH = VER + CH_PRECISION + [
    'void main(){}',
    ''].join('\n');

  /* ============================ MAIN PBR =============================== */
  var VS_PBR = VER + CH_FRAME + [
    'layout(location = 0) in vec3 aPos;',
    'layout(location = 1) in vec3 aNrm;',
    'layout(location = 2) in vec2 aUV;',
    'layout(location = 3) in vec3 aCol;',
    'uniform mat4 uModel;',
    'uniform mat3 uNrmMat;',
    'out vec3 vWPos;',
    'out vec3 vNrm;',
    'out vec2 vUV;',
    'out vec3 vCol;',
    'out float vViewZ;',
    'void main(){',
    '  vec4 wp = uModel * vec4(aPos, 1.0);',
    '  vWPos = wp.xyz;',
    '  vNrm = normalize(uNrmMat * aNrm);',
    '  vUV = aUV;',
    '  vCol = aCol;',
    '  vec4 vp = uView * wp;',
    '  vViewZ = -vp.z;',
    '  gl_Position = uProj * vp;',
    '}',
    ''].join('\n');

  var FS_PBR = VER + CH_PRECISION_SHADOWSAMP + CH_FRAME + CH_LIGHTS + CH_PBR + CH_FOG + [
    'in vec3 vWPos;',
    'in vec3 vNrm;',
    'in vec2 vUV;',
    'in vec3 vCol;',
    'in float vViewZ;',
    'out vec4 oCol;',
    '',
    'uniform sampler2DArray uTexAlbedo;',
    'uniform sampler2DArray uTexNormal;',
    'uniform sampler2DArray uTexORM;',
    'uniform sampler2DArrayShadow uShadowMap;',
    'uniform samplerCube uEnv;',
    'uniform sampler2D uAOTex;',
    'uniform vec4 uAlbedo;      // rgb base colour, a = alpha',
    'uniform vec4 uMatParams;   // x rough, y metal, z texLayer(-1=none), w texScale',
    'uniform vec4 uEmissive;    // rgb emissive (already pulse-modulated), w unused',
    '',
    '// ---------------- triplanar material sampling ----------------------',
    'void triplanar(vec3 wp, vec3 N, float layer, float scale,',
    '               out vec4 alb, out vec3 nrm, out vec3 orm){',
    '  vec3 bw = abs(N);',
    '  bw = pow(bw, vec3(4.0));',
    '  bw /= max(bw.x + bw.y + bw.z, 1e-4);',
    '  vec2 uvX = wp.zy * scale;',
    '  vec2 uvY = wp.xz * scale;',
    '  vec2 uvZ = wp.xy * scale;',
    '  if (uMisc.x < 0.5) {',
    '    // quality 0: single dominant-axis projection (1 tap per map)',
    '    bool ax = (bw.x > bw.y && bw.x > bw.z);',
    '    bool ay = (!ax && bw.y > bw.z);',
    '    vec2 uv = ax ? uvX : (ay ? uvY : uvZ);',
    '    alb = texture(uTexAlbedo, vec3(uv, layer));',
    '    orm = texture(uTexORM, vec3(uv, layer)).xyz;',
    '    vec3 tn = texture(uTexNormal, vec3(uv, layer)).xyz * 2.0 - 1.0;',
    '    vec3 sn0 = sign(N);',
    '    vec3 wn = ax ? vec3(0.0, tn.y, tn.x) * sn0.x',
    '                 : (ay ? vec3(tn.x, 0.0, tn.y) * sn0.y : vec3(tn.x, tn.y, 0.0) * sn0.z);',
    '    nrm = normalize(N + wn);',
    '    return;',
    '  }',
    '  vec4 aX = texture(uTexAlbedo, vec3(uvX, layer));',
    '  vec4 aY = texture(uTexAlbedo, vec3(uvY, layer));',
    '  vec4 aZ = texture(uTexAlbedo, vec3(uvZ, layer));',
    '  alb = aX * bw.x + aY * bw.y + aZ * bw.z;',
    '  vec3 oX = texture(uTexORM, vec3(uvX, layer)).xyz;',
    '  vec3 oY = texture(uTexORM, vec3(uvY, layer)).xyz;',
    '  vec3 oZ = texture(uTexORM, vec3(uvZ, layer)).xyz;',
    '  orm = oX * bw.x + oY * bw.y + oZ * bw.z;',
    '  // UDN-style triplanar normal blend',
    '  vec3 nX = texture(uTexNormal, vec3(uvX, layer)).xyz * 2.0 - 1.0;',
    '  vec3 nY = texture(uTexNormal, vec3(uvY, layer)).xyz * 2.0 - 1.0;',
    '  vec3 nZ = texture(uTexNormal, vec3(uvZ, layer)).xyz * 2.0 - 1.0;',
    '  vec3 sn = sign(N);',
    '  vec3 wX = vec3(0.0, nX.y, nX.x) * sn.x;',
    '  vec3 wY = vec3(nY.x, 0.0, nY.y) * sn.y;',
    '  vec3 wZ = vec3(nZ.x, nZ.y, 0.0) * sn.z;',
    '  nrm = normalize(N + wX * bw.x + wY * bw.y + wZ * bw.z);',
    '}',
    '',
    '// ---------------- cascaded shadows ---------------------------------',
    'float sampleShadow(vec3 wp, vec3 N, float ndl, float viewZ, out int cascOut){',
    '  if (uSunCol.w < 0.01) { cascOut = 0; return 1.0; }',
    '  int c = 0;',
    '  if (viewZ > uCascadeSplits.x) c = 1;',
    '  if (viewZ > uCascadeSplits.y) c = 2;',
    '  cascOut = c;',
    '  mat4 m = uCascade0;',
    '  if (c == 1) m = uCascade1;',
    '  else if (c == 2) m = uCascade2;',
    '  float cs = 1.0 + float(c) * 1.4;',
    '  // normal offset scales with slope and cascade texel size',
    '  float slope = clamp(1.0 - ndl, 0.0, 1.0);',
    '  vec3 offP = wp + N * (uMisc2.y * cs * (0.35 + slope * 1.65));',
    '  vec4 sc = m * vec4(offP, 1.0);',
    '  vec3 pr = sc.xyz / max(sc.w, 1e-5);',
    '  pr = pr * 0.5 + 0.5;',
    '  if (pr.z >= 1.0 || pr.x < 0.0 || pr.x > 1.0 || pr.y < 0.0 || pr.y > 1.0) return 1.0;',
    '  float bias = uMisc2.z * cs * (1.0 + slope * 3.0);',
    '  float ref = pr.z - bias;',
    '  float texel = uMisc2.w;',
    '  float s = 0.0;',
    '  int R = int(uMisc.x) >= 2 ? 2 : 1;',
    '  float cnt = 0.0;',
    '  for (int y = -2; y <= 2; y++){',
    '    if (y < -R || y > R) continue;',
    '    for (int x = -2; x <= 2; x++){',
    '      if (x < -R || x > R) continue;',
    '      vec2 o = vec2(float(x), float(y)) * texel;',
    '      s += texture(uShadowMap, vec4(pr.xy + o, float(c), ref));',
    '      cnt += 1.0;',
    '    }',
    '  }',
    '  s /= max(cnt, 1.0);',
    '  // fade the last cascade out at its far edge so the terminator is soft',
    '  float fade = 1.0 - smoothstep(uCascadeSplits.z * 0.82, uCascadeSplits.z, viewZ);',
    '  return mix(1.0, s, fade);',
    '}',
    '',
    'void main(){',
    '  vec3 N = normalize(vNrm);',
    '  vec3 V = normalize(uCamPos.xyz - vWPos);',
    '  if (!gl_FrontFacing) N = -N;',
    '',
    '  vec3 baseCol = uAlbedo.rgb * vCol;',
    '  float rough = uMatParams.x;',
    '  float metal = uMatParams.y;',
    '  float ao = 1.0;',
    '  float alpha = uAlbedo.a;',
    '',
    '  if (uMatParams.z >= 0.0){',
    '    vec4 ta; vec3 tn; vec3 to;',
    '    triplanar(vWPos, N, uMatParams.z, uMatParams.w, ta, tn, to);',
    '    baseCol *= ta.rgb * ta.rgb * 2.0;   // undo the sqrt encode, keep midtones',
    '    alpha *= ta.a;',
    '    N = tn;',
    '    ao = to.x;',
    '    rough = clamp(rough * (0.35 + to.y * 1.15), 0.03, 1.0);',
    '    metal = clamp(max(metal, to.z * 0.92), 0.0, 1.0);',
    '  }',
    '  if (alpha < 0.35 && uAlbedo.a >= 0.999) discard;   // alpha-cut foliage/grate',
    '',
    '  float NoV = clamp(dot(N, V), 1e-4, 1.0);',
    '  vec3 f0 = mix(vec3(0.04), baseCol, metal);',
    '  vec3 diffCol = baseCol * (1.0 - metal);',
    '  float a = max(rough * rough, 1e-3);',
    '',
    '  vec3 direct = vec3(0.0);',
    '',
    '  // ---- sun ---------------------------------------------------------',
    '  vec3 L = normalize(uSunDir.xyz);',
    '  float NoL = dot(N, L);',
    '  int casc = 0;',
    '  if (NoL > 0.0){',
    '    float sh = sampleShadow(vWPos, N, NoL, vViewZ, casc);',
    '    if (sh > 0.001){',
    '      vec3 H = normalize(L + V);',
    '      float NoH = clamp(dot(N, H), 0.0, 1.0);',
    '      float VoH = clamp(dot(V, H), 0.0, 1.0);',
    '      vec3 F = F_Schlick(f0, VoH);',
    '      float D = D_GGX(NoH, a);',
    '      float Vs = V_SmithGGX(NoV, NoL, a);',
    '      vec3 spec = F * (D * Vs);',
    '      vec3 kd = (vec3(1.0) - F);',
    '      direct += (kd * diffCol / PI + spec) * uSunCol.rgb * uSunDir.w * NoL * sh;',
    '    }',
    '  }',
    '',
    '  // ---- punctual lights (CPU distance-culled into the UBO) -----------',
    '  int n = int(uMisc.y + 0.5);',
    '  for (int i = 0; i < 48; i++){',
    '    if (i >= n) break;',
    '    vec3 lp = uLightPos[i].xyz;',
    '    vec3 dv = lp - vWPos;',
    '    float d2 = dot(dv, dv);',
    '    float range = uLightPos[i].w;',
    '    if (d2 > range * range) continue;',
    '    float dist = sqrt(max(d2, 1e-8));',
    '    vec3 Lp = dv / dist;',
    '    float nl = dot(N, Lp);',
    '    if (nl <= 0.0) continue;',
    '    float att = lightAtten(dist, range);',
    '    vec3 H = normalize(Lp + V);',
    '    float NoH = clamp(dot(N, H), 0.0, 1.0);',
    '    float VoH = clamp(dot(V, H), 0.0, 1.0);',
    '    vec3 F = F_Schlick(f0, VoH);',
    '    float D = D_GGX(NoH, a);',
    '    float Vs = V_SmithGGX(NoV, nl, a);',
    '    vec3 spec = F * (D * Vs);',
    '    vec3 kd = (vec3(1.0) - F);',
    '    direct += (kd * diffCol / PI + spec) * uLightCol[i].rgb * (att * nl);',
    '  }',
    '',
    '  // ---- image based ambient -----------------------------------------',
    '  float ssao = 1.0;',
    '  if (uMisc.w > 0.5){',
    '    ssao = texture(uAOTex, gl_FragCoord.xy * uScreen.zw).r;',
    '  }',
    '  float occ = ao * mix(1.0, ssao, clamp(uAmbient.w, 0.0, 1.0));',
    '  vec3 R = reflect(-V, N);',
    '  float mipMax = float(' + (ENV_MIPS - 1) + ');',
    '  vec3 irr = textureLod(uEnv, N, mipMax).rgb;',
    '  vec3 pref = textureLod(uEnv, R, rough * mipMax).rgb;',
    '  vec2 ab = envBRDF(NoV, rough);',
    '  vec3 ambDiff = (irr + uAmbient.rgb) * diffCol * occ;',
    '  vec3 ambSpec = pref * (f0 * ab.x + ab.y) * occ;',
    '  // horizon occlusion keeps grazing reflections from lighting up caves',
    '  float ho = clamp(1.0 + dot(R, N), 0.0, 1.0); ho *= ho;',
    '  ambSpec *= ho;',
    '',
    '  // ---- rim / fresnel so silhouettes read in the dark ----------------',
    '  float rim = pow(1.0 - NoV, 3.5);',
    '  vec3 rimCol = (uAmbient.rgb * 6.0 + uFogCol.rgb * 3.0) * rim * (0.35 + 0.65 * (1.0 - rough));',
    '',
    '  vec3 col = direct + ambDiff + ambSpec + rimCol + uEmissive.rgb;',
    '',
    '  // ---- lightning bounce ---------------------------------------------',
    '  col += diffCol * uMisc2.x * (0.5 + max(N.y, 0.0) * 1.6) * 0.9;',
    '',
    '  // ---- fog ----------------------------------------------------------',
    '  float fg = heightFog(uCamPos.xyz, vWPos);',
    '  vec3 fogc = uFogCol.rgb * (1.0 + uMisc2.x * 5.0);',
    '  // cheap sun-inscatter tint towards the light',
    '  float vl = max(dot(normalize(vWPos - uCamPos.xyz), L), 0.0);',
    '  fogc += uSunCol.rgb * pow(vl, 6.0) * 0.35 * uSunDir.w;',
    '  col = mix(col, fogc, fg);',
    '',
    '  // cascade debug tint (uAmbient.w is driven negative by debug.showCascades)',
    '  if (uAmbient.w < -0.5){',
    '    casc = 0;',
    '    if (vViewZ > uCascadeSplits.x) casc = 1;',
    '    if (vViewZ > uCascadeSplits.y) casc = 2;',
    '    vec3 tint = casc == 0 ? vec3(1.0, 0.3, 0.3) : (casc == 1 ? vec3(0.3, 1.0, 0.3) : vec3(0.3, 0.4, 1.0));',
    '    col = mix(col, tint * (0.2 + length(col) * 0.4), 0.55);',
    '  }',
    '',
    '  oCol = vec4(max(col, vec3(0.0)), alpha);',
    '}',
    ''].join('\n');

  /* Unlit fallback - used only if the PBR program fails to compile/link. */
  var FS_FALLBACK = VER + CH_PRECISION + CH_FRAME + [
    'in vec3 vWPos;',
    'in vec3 vNrm;',
    'in vec2 vUV;',
    'in vec3 vCol;',
    'in float vViewZ;',
    'out vec4 oCol;',
    'uniform vec4 uAlbedo;',
    'uniform vec4 uMatParams;',
    'uniform vec4 uEmissive;',
    'void main(){',
    '  vec3 N = normalize(vNrm);',
    '  float d = max(dot(N, normalize(uSunDir.xyz)), 0.0) * 0.8 + 0.2;',
    '  oCol = vec4(uAlbedo.rgb * vCol * d + uEmissive.rgb, uAlbedo.a);',
    '}',
    ''].join('\n');

  /* == SECTION_MARKER_2 == */

  IP.Renderer = null;
})();
